<a href="https://colab.research.google.com/github/Ayseguldeniz/bookstore-project/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [3]:
import numpy as np
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [4]:
samples = np.random.normal(100, 15, 1000)
samples

array([ 98.25927317,  86.33331955, 119.10846649,  91.55807183,
       108.87370488, 104.3350779 ,  97.84082549,  99.67587978,
       117.14318062, 131.55177303,  81.93056676, 100.37926166,
       100.30205382, 113.19856858,  88.00443177, 110.24317862,
       116.81915197, 104.57909016,  79.62553963,  83.06823111,
       119.44441377, 113.46488544,  95.2717922 , 116.54799051,
       101.6147828 , 110.57258873,  95.95523453,  94.16055721,
       112.54348941, 116.90162568,  99.04122666, 119.00198431,
        90.64087912, 104.58019996,  91.71404518,  99.93125018,
        89.30875452,  90.46573065, 110.67733899,  95.45542112,
        98.78139239, 112.07447005, 109.83421055,  78.03070386,
       105.25735462, 102.71289735,  85.23893877,  97.8789776 ,
       117.66472662, 103.47924231, 123.67594986, 100.29318097,
        90.08101996,  95.29716004, 111.70901872,  97.41420051,
        99.68503806, 103.56046083, 105.27529752, 102.91101148,
        75.29219746, 112.1530753 , 112.83679507, 113.08

Compute the **mean**, **median**, and **mode**

In [6]:
mean = np.mean(samples)
median =np.median(samples)
mode = stats.mode(samples)

In [7]:
mean

99.97241341934871

In [8]:
median

99.87846578421806

In [9]:
mode

ModeResult(mode=array([53.8387331]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [10]:
min = np.min(samples)
min

53.83873310352262

In [11]:
max = np.max(samples)
max

148.2251357775158

In [12]:
q1 = median - min
q1

46.039732680695444

In [13]:
q3 = max - median
q3

48.34666999329772

In [15]:
iqr = q3 - q1
iqr

2.3069373126022796

Compute the **variance** and **standard deviation**

In [16]:
variance = np.var(samples)
variance

212.19087751334882

In [17]:
std_dev =np.std(samples)
std_dev

14.566773064524236

Compute the **skewness** and **kurtosis**

In [ ]:
skewness =
kurtosis =

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [18]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [19]:
y = np.random.randint(x, size = 10)
y

array([ 1,  4,  6, 12,  8,  5, 11,  6, 11,  5])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [20]:
numer = len(x)*sum(x*y) - sum(x)*sum(y)
denom = np.sqrt((len(x)*sum(x**2)-sum(x)**2)*(len(y)*sum(y**2)-sum(y)**2))
r = numer/denom
r

0.40928247625406045

## Pandas Correlation Calculation

Run the code below

In [21]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [22]:
print("correlation: ", np.corrcoef(x,y))

correlation:  [[1.         0.75864029]
 [0.75864029 1.        ]]


OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =

## Seaborn Dataset Tips

Import Seaborn Library

In [23]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [24]:
tip = sns.load_dataset("tips")
tip 

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [25]:
tip.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns